src/Entity/Livres.php
<?php

namespace App\Entity;

use App\Repository\LivresRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LivresRepository::class)
 */
class Livres
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $auteur_livre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_livre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_livre;

    /**
     * @ORM\ManyToOne(targetEntity=Genres::class, inversedBy="livres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $genre_livre;

    /**
     * @ORM\ManyToOne(targetEntity=Formats::class, inversedBy="livres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $format_livre;

    /**
     * @ORM\ManyToOne(targetEntity=EtatsUsure::class, inversedBy="livres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etat_livre;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="livres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $vendeur_livre;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_livre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_annonce_livre;


    public function getId(): ?int
    {
        return $this->id;
    }


    public function getAuteurLivre(): ?string
    {
        return $this->auteur_livre;
    }

    public function setAuteurLivre(string $auteur_livre): self
    {
        $this->auteur_livre = $auteur_livre;

        return $this;
    }

    public function getTitreLivre(): ?string
    {
        return $this->titre_livre;
    }

    public function setTitreLivre(string $titre_livre): self
    {
        $this->titre_livre = $titre_livre;

        return $this;
    }

    public function getImageLivre(): ?string
    {
        return $this->image_livre;
    }

    public function setImageLivre(string $image_livre): self
    {
        $this->image_livre = $image_livre;

        return $this;
    }

    public function getGenreLivre(): ?Genres
    {
        return $this->genre_livre;
    }

    public function setGenreLivre(?Genres $genre_livre): self
    {
        $this->genre_livre = $genre_livre;

        return $this;
    }

    public function getFormatLivre(): ?Formats
    {
        return $this->format_livre;
    }

    public function setFormatLivre(?Formats $format_livre): self
    {
        $this->format_livre = $format_livre;

        return $this;
    }

    public function getEtatLivre(): ?EtatsUsure
    {
        return $this->etat_livre;
    }

    public function setEtatLivre(?EtatsUsure $etat_livre): self
    {
        $this->etat_livre = $etat_livre;

        return $this;
    }

    public function getVendeurLivre(): ?User
    {
        return $this->vendeur_livre;
    }

    public function setVendeurLivre(?User $vendeur_livre): self
    {
        $this->vendeur_livre = $vendeur_livre;

        return $this;
    }

    public function getPrixLivre(): ?float
    {
        return $this->prix_livre;
    }

    public function setPrixLivre(float $prix_livre): self
    {
        $this->prix_livre = $prix_livre;

        return $this;
    }

    public function getDateAnnonceLivre(): ?\DateTimeInterface
    {
        return $this->date_annonce_livre;
    }

    public function setDateAnnonceLivre(\DateTimeInterface $date_annonce_livre): self
    {
        $this->date_annonce_livre = $date_annonce_livre;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Livres::class, mappedBy="vendeur_livre")
     */
    private $livres;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom_utilisateur;

    public function __construct()
    {
        $this->livres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Livres>
     */
    public function getLivres(): Collection
    {
        return $this->livres;
    }

    public function addLivre(Livres $livre): self
    {
        if (!$this->livres->contains($livre)) {
            $this->livres[] = $livre;
            $livre->setVendeurLivre($this);
        }

        return $this;
    }

    public function removeLivre(Livres $livre): self
    {
        if ($this->livres->removeElement($livre)) {
            // set the owning side to null (unless already changed)
            if ($livre->getVendeurLivre() === $this) {
                $livre->setVendeurLivre(null);
            }
        }

        return $this;
    }

    public function getPrenomUtilisateur(): ?string
    {
        return $this->prenom_utilisateur;
    }

    public function setPrenomUtilisateur(string $prenom_utilisateur): self
    {
        $this->prenom_utilisateur = $prenom_utilisateur;

        return $this;
    }

    public function __toString(){
        return $this->prenom_utilisateur;
    }
}

src/Form/LivresType.php
<?php

namespace App\Form;

use App\Entity\EtatsUsure;
use App\Entity\Formats;
use App\Entity\Genres;
use App\Entity\Livres;
use App\Entity\User;

use Symfony\Component\Form\AbstractType;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;


use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;



class LivresType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder

            ->add('genre_livre', EntityType::class, [
                'class' => Genres::class,
                'choice_label' => 'genre',
                'label' => 'Genre',
                'required' => true
            ])


            ->add('auteur_livre', TextType::class, [
                'required' => true
            ])


            ->add('titre_livre', TextType::class, [
                'required' => true
            ])


            ->add('image_livre', FileType::class, [
                'label' => 'Image du livre',
                'required' => true,
                'data_class' => null,
                'empty_data' => 'Aucune image pour ce livre!'
            ])


            ->add('format_livre', EntityType::class, [
                'class' => Formats::class,
                'choice_label' => 'format',
                'label' => 'Sélectionnez un format',
                'required' => true,

            ])


            ->add('vendeur_livre', EntityType::class, [
                'class' => User::class,
                'choice_label' => 'email',
                'label' => 'Vendu par',
                'required' => true
            ])


            ->add('etat_livre', EntityType::class, [
                'class' => EtatsUsure::class,
                'choice_label' => 'Etat',
                'label' => 'Sélectionnez l\'état d\'usure du livre',
            ])


            ->add('prix_livre', NumberType::class, [
                'required' => true
            ])


            ->add('date_annonce_livre', DateType::class, [
                'required' => true
            ]);

    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Livres::class,
        ]);
    }
}

src/Controller/LivresController.php
<?php

namespace App\Controller;

use App\Entity\Livres;
use App\Form\LivresType;
use App\Repository\LivresRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/livres")
 */
class LivresController extends AbstractController
{
    /**
     * @Route("/", name="app_livres_index", methods={"GET"})
     */
    public function index(LivresRepository $livresRepository): Response
    {
        return $this->render('livres/index.html.twig', [
            'livres' => $livresRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_livres_new", methods={"GET", "POST"})
     */
    public function new(Request $request, LivresRepository $livresRepository): Response
    {
        $livre = new Livres();
        $form = $this->createForm(LivresType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $form["image_livre"]->getData();

            if (!is_string($file)) {
                $fileName = $file->getClientOriginalName();

                $file->move(
                    $this->getParameter('images_directory'),
                    $fileName
                );


                $livre->setImageLivre($fileName);


                //$this->addFlash('success', 'Le livre a bien été ajouté');

            } else {
                //$this->addFlash('danger', 'Une erreur est survenue');
                return $this->redirect($this->generateUrl('app_livres_new'));

            }

            $livresRepository->add($livre, true);
            return $this->redirectToRoute('app_livres_index', [], Response::HTTP_SEE_OTHER);

        }
        return $this->renderForm('livres/new.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_livres_show", methods={"GET"})
     */
    public function show(Livres $livre): Response
    {
        return $this->render('livres/show.html.twig', [
            'livre' => $livre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_livres_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Livres $livre, LivresRepository $livresRepository): Response
    {

        $img = $livre->getImageLivre();

        $form = $this->createForm(LivresType::class, $livre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $form["image_livre"]->getData();

            if (!is_string($file)) {
                $fileName = $file->getClientOriginalName();

                $file->move(
                    $this->getParameter('images_directory'),

                    $fileName
                );


                $livre->setImageLivre($fileName);


                //$this->addFlash('success', 'Le livre a bien été ajouté');

            } else {
                //$this->addFlash('danger', 'Une erreur est survenue');
                $livre->setImageLivre($img);

            }

            $livresRepository->add($livre, true);

            return $this->redirectToRoute('app_livres_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('livres/edit.html.twig', [
            'livre' => $livre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_livres_delete", methods={"POST"})
     */
    public function delete(Request $request, Livres $livre, LivresRepository $livresRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$livre->getId(), $request->request->get('_token'))) {
            $livresRepository->remove($livre, true);
        }

        return $this->redirectToRoute('app_livres_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/livres/_delete_form.html.twig
<form method="post" action="{{ path('app_livres_delete', {'id': livre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ livre.id) }}">
    <button id="btn-supp-crud" class="btn mt-2">SUPPRIMER</button>
</form>

templates/livres/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success mt-3">{{ button_label|default('VALIDER') }}</button>
{{ form_end(form) }}

templates/livres/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Livres{% endblock %}

{% block body %}
    <h1>Edit Livres</h1>

    {{ include('livres/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-light mt-2" href="{{ path('app_livres_index') }}">Retour</a>


{% endblock %}

templates/livres/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres index{% endblock %}

{% block body %}

    {% if app.user %}
    <h2 class="text-center">Mes livres</h2>

        <a class="btn btn-light bg-dark text-info mb-3" href="{{ path('app_livres_new') }}">Ajouter un livre</a>

    <table id="form-inscription" class="table text-white">

        <thead>
            <tr>
                <th>ID</th>
                <th>Genre</th>
                <th>Auteur</th>
                <th>Titre</th>
                <th>Image</th>
                <th>Format</th>
                <th>Vendeur</th>
                <th>Etat</th>
                <th>Prix</th>
                <th>Date annonce</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for livre in app.user.livres %}
            <tr>

                <td>{{ livre.id }}</td>
                <td>{{ livre.genreLivre }}</td>
                <td>{{ livre.auteurLivre }}</td>
                <td>{{ livre.titreLivre }}</td>
                <td><img class="w-50" src="/img/Livres-en-ligne{{asset(livre.imageLivre)}}" alt="{{ livre.titreLivre }}" title="{{ livre.titreLivre }}"></td>
                <td>{{ livre.formatLivre }}</td>
                <td>{{ livre.vendeurLivre.prenomUtilisateur }}</td>
                <td>{{ livre.etatLivre }}</td>
                <td>{{ livre.prixLivre }}€</td>
                <td>{{ livre.dateAnnonceLivre | date('d/m/Y') }}</td>
                <td>
                    {% if is_granted('ROLE_USER') %}
                        <a id="btn-crud" class="btn btn-large btn-light" href="{{ path('app_livres_show', {'id': livre.id}) }}">Détails</a>
                        <a id="btn-crud" class="btn btn-large btn-light" href="{{ path('app_livres_edit', {'id': livre.id}) }}">Editer</a>
                        <div class="col-4 text-center mt-2">
                            {{include('livres/_delete_form.html.twig')}}
                        </div>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Pas de résultat(s)</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

        <a class="btn btn-large btn-light bg-dark text-info mb-3" href="{{ path('app_livres_new') }}">Ajouter un livre</a>


    {% else %}
        <div>
            <h2>Vous devez être connecté pour accéder à vos annonces</h2>
        </div>

    {% endif %}

{% endblock %}

templates/livres/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Livres{% endblock %}

{% block body %}
        <div id="form-edit-livres" class="w-50 text-white">
            <h2 class="text-white mb-4">Ajouter un livre</h2>

            <div class="w-75">
                {{ include('livres/_form.html.twig') }}
            </div>

            <a class="btn btn-danger mt-2" href="{{ path('app_livres_index') }}">Annuler</a>
        </div>


{% endblock %}

templates/livres/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livres{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-4">
            <div id="card-details-livre" class="card">


                <div id="card-title-titre" class="card-title p-2 text-center text-white">{{ livre.titreLivre }}</div>
                <div id="card-title-auteur" class="card-title p-1 text-white">{{ livre.auteurLivre }}</div>
                <div id="card-title-genre" class="card-title p-1 text-white">{{ livre.genreLivre }}</div>

                <div class="row m-0 p-0">
                    <div class="card-body col-5">
                        <div class="card-img"><img src="/img/Livres-en-ligne{{asset(livre.imageLivre)}}" class="img-fluid"></div>
                    </div>
                    <div class="card-body col-7">
                        <div class="card-text"><p class="p-0 m-0 bg-dark text-white">Vendu par:</p> <p>{{ livre.vendeurLivre }}</p></div>
                        <div class="card-text"><p class="p-0 m-0 bg-dark text-white">Etat du livre:</p> <p>{{ livre.etatLivre }}</p></div>
                        <div class="card-text"><p class="p-0 m-0 bg-dark text-white">Prix TTC:</p> <p>{{ livre.prixLivre }}€</p></div>
                        <div class="card-text"><p class="p-0 m-0 bg-dark text-white">Date de l'annonce:</p> <p>{{ livre.dateAnnonceLivre | date("d/m/Y")}}</p></div>
                    </div>
                </div>

                {% if is_granted('ROLE_USER') %}
                    <div class="card-footer">
                        <div class="row align-items-center">
                            <div class="col-4 text-center">
                                {{include('livres/_delete_form.html.twig')}}
                            </div>
                            <div class="col-4 text-center">
                                <a id="btn-crud" class="btn btn-large btn-light" href="{{ path('app_livres_edit', {'id': livre.id}) }}">EDITER</a>
                            </div>
                            <div class="col-4 text-center">
                                <a id="btn-crud" class="btn btn-large btn-light" href="{{ path('app_livres_index') }}">RETOUR</a>
                            </div>
                        </div>
                    </div>
                {% endif %}


            </div>
        </div>
    </div>



{% endblock %}